add micropython and circuitpython with xiao esp32
Seeed-Studio/wiki-documents pull request #1554
Opened 2024-08-14 09:27 UTC by cure123123

2024-08-15 08:26 UTC, limengdu requested changes

2024-08-15 08:26 UTC, limengdu commented on sidebars.js
>              'Sensor/SeeedStudio_XIAO/SeeedStudio_XIAO_ESP32C3/XIAO_ESP32C3_MicroPython',
检查一下旧的wiki还有没有存在的必要，如果没有，在sidebar里面移除

2024-08-15 08:26 UTC, limengdu commented on docs/Sensor/SeeedStudio_XIAO/SeeedStudio_XIAO_ESP32C3/XIAO_ESP32C3_with_CircuitPython.md
> +## Getting Started with CircuitPython on the ESP32-C3
改产品名：XIAO ESP32C3

2024-08-15 08:26 UTC, limengdu commented on docs/Sensor/SeeedStudio_XIAO/SeeedStudio_XIAO_ESP32C3/XIAO_ESP32C3_with_CircuitPython.md
> +##### Download and Extract the Library Bundle:
在Wiki里面尽量不要去用五级标题

2024-08-15 08:26 UTC, limengdu commented on docs/Sensor/SeeedStudio_XIAO/SeeedStudio_XIAO_ESP32C3/XIAO_ESP32C3_with_MicroPython.md
> +# **Seeed Studio XIAO ESP32-C3 with MicroPython**
XIAO ESP32C3，不要自己改产品名称

2024-08-15 08:26 UTC, limengdu commented on docs/Sensor/SeeedStudio_XIAO/SeeedStudio_XIAO_ESP32C3/XIAO_ESP32C3_with_MicroPython.md
> +#### Connect the ESP32-C3 on your PC
XIAO ESP32C3

2024-08-15 08:26 UTC, limengdu commented on docs/Sensor/SeeedStudio_XIAO/SeeedStudio_XIAO_ESP32C3/XIAO_ESP32C3_with_CircuitPython.md
> +## Tech Support & Product Discussion
加一个resource二级标题，提供一下固件的下载链接

2024-08-15 08:48 UTC, cure123123 commented on sidebars.js
>              'Sensor/SeeedStudio_XIAO/SeeedStudio_XIAO_ESP32C3/XIAO_ESP32C3_MicroPython',
有 不一样的 可以给其改个名字

2024-08-15 08:48 UTC, cure123123 commented on docs/Sensor/SeeedStudio_XIAO/SeeedStudio_XIAO_ESP32C3/XIAO_ESP32C3_with_CircuitPython.md
> +## Getting Started with CircuitPython on the ESP32-C3
done

2024-08-15 08:48 UTC, cure123123 commented on docs/Sensor/SeeedStudio_XIAO/SeeedStudio_XIAO_ESP32C3/XIAO_ESP32C3_with_CircuitPython.md
> +##### Download and Extract the Library Bundle:
done

2024-08-15 08:48 UTC, cure123123 commented on docs/Sensor/SeeedStudio_XIAO/SeeedStudio_XIAO_ESP32C3/XIAO_ESP32C3_with_MicroPython.md
> +# **Seeed Studio XIAO ESP32-C3 with MicroPython**
done

2024-08-15 08:48 UTC, cure123123 commented on docs/Sensor/SeeedStudio_XIAO/SeeedStudio_XIAO_ESP32C3/XIAO_ESP32C3_with_MicroPython.md
> +#### Connect the ESP32-C3 on your PC
done

2024-08-15 08:48 UTC, cure123123 commented on docs/Sensor/SeeedStudio_XIAO/SeeedStudio_XIAO_ESP32C3/XIAO_ESP32C3_with_CircuitPython.md
> +## Tech Support & Product Discussion
链接都在里面了 还要单独列出来？

2024-08-16 01:12 UTC, limengdu commented on sidebars.js
>              'Sensor/SeeedStudio_XIAO/SeeedStudio_XIAO_ESP32C3/XIAO_ESP32C3_MicroPython',
能不能合并在一起？同一主题的内容，就不需要两篇了

2024-08-19 01:47 UTC, limengdu approved these changes

2024-08-19 02:13 UTC, merged