Update XIAO_ESP32S3_CircuitPython.md
Seeed-Studio/wiki-documents pull request #1584
Opened 2024-08-19 16:02 UTC by djairjr

Adding instructions to burn custom firmware in Thonny, links to both firmwares, code to work with espcamera and Xiao Round Display.

2024-08-20 01:27 UTC, limengdu requested changes

2024-08-20 01:27 UTC, limengdu commented on docs/Sensor/SeeedStudio_XIAO/SeeedStudio_XIAO_ESP32S3/XIAO_ESP32S3_CircuitPython.md
> +  date: 18/08/2024
08/18/2024

2024-08-20 01:28 UTC, limengdu commented
@cure123123 please try this wiki

2024-08-20 08:19 UTC, cure123123 commented
@djairjr Hi, thanks for your contribution to wiki. When I reworked ur code with the round display and XIAO ESP32S3 sense, I found the" espcamera" isn't included in the adafruit bundle library either the supported module of board(ESP32-S3-DevKitC-1-N8). May I ask which firmware u burned for XIAO and how to get the espcamera module? Thank you.

2024-08-20 08:47 UTC, MatthewJeffson commented
Hello! @cure123123 The firmware file is here: https://github.com/djairjr/Seeed_Xiao_ESPS3_Sense_Circuitpython/tree/main/seeed_xiao_esp32s3_sense/seeed_xiao_esp32s3_sense

2024-08-22 09:53 UTC, cure123123 commented
Hi @djairjr  Well Done! Thank you for ur work, can u add the firmware to wiki and need to verify the date format with month/day/year.

2024-08-24 10:42 UTC, MatthewJeffson commented
I have updated the url and it should be fine now

2024-08-26 05:37 UTC, merged